name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: | 
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
          # git clone git@github:rizgithub:$GITHUB_REPOSTORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: List Files after Checkout Action Usage
        run: | 
          pwd
          ls -la
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: Rizwan
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time}}"